# Minimum hugo version required: 0.32

BaseUrl: https://www.vibrobox.com/
DefaultContentLanguage: en
ContentDir: content
PublishDir: docs
StaticDir: static/common

BuildDrafts: true
BuildExpired: true
BuildFuture: true
DefaultContentLanguageInSubdir: false
EnableMissingTranslationPlaceholders: true
MetadataFormat: yaml
DisableKinds: [taxonomy, taxonomyTerm, RSS]
I18nDir: translations
Logi18nwarnings: true
# Correct lastmod time for pages in sitemap.
EnableGitInfo: true
# Open all external links from content in a new window.
BlackFriday:
  hrefTargetBlank: true
  #laxHtmlBlocks: true

# Urls with year and month for the news section.
# Title or file name will be used if slug is not defined in the post frontmatter.
Permalinks:
  news: /news/:year/:month/:slug/

# The name of the news section, used in templates and in Open Graph.
# Can be localized when hugo will support localized section names.
Params:
  news_section: news
  team_section: team
  facebook_author_profile: https://www.facebook.com/VibroBox

Languages:
  en:
    Weight: 1
    LanguageName: English
    LanguageCode: en
    locale: en_US
    Title: In English
    GoogleAnalytics: UA-79782596-1
    Copyright: © 2018 VibroBox OÜ
    Description: TODO Default English description
    # Hugo treats keywords in pages as an array, so here we also specify it as an array.
    # Simple syntax should be used in pages - Keywords: keywords, without, quotes, and, braces
    Keywords: ["TODO, default, keywords"]
    StaticDir2: static/en
    demourl: https://demo.vibrobox.com/demo?locale=en
    dateformat: "January 02, 2006"
  ru:
    BaseUrl: https://www.vibrobox.ru/
    Weight: 2
    LanguageName: Русский
    LanguageCode: ru
    locale: ru_RU
    Title: На русском
    GoogleAnalytics: UA-79782596-2
    BlackFriday:
      angledQuotes: true
    Copyright: © 2018 VibroBox
    Description: TODO Описание страницы на русском по-умолчанию, для всего сайта
    Keywords: ["TODO, ключевые, слова, по-умолчанию"]
    StaticDir2: static/ru
    demourl: https://demo.vibrobox.com/demo?locale=ru
    dateformat: "02 January 2006"
    # TODO: Uncommend when section localization bug will be fixed (see news/_index.ru.md for details).
    #permalinks:
    #  news: /новости/:year/:month/:slug/
